### ISSUE TITLE
SingleOrDefault to FirstOrDefault

### ISSUE THREAD

**Issue by AmineTissilguit** [ID-JA/2tinylink#22]
- Use `FirstOrDefault` instead of `SingleOrDefault`.

**Comment by ID-JA** [comment]
Fixed 
https://github.com/ID-JA/2tinylink/blob/de246b4b95b828524b202f3ca2cfc01203c121ff/server/src/Application/UseCases/CorrespondedUrl/Queries/UrlByAddress/UrlByAddressQueryHandler.cs#L23
